# Generated by Django 5.2.1 on 2025-06-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_producto_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos_imagenes/'),
        ),
    ]
