# Generated by Django 5.2.1 on 2025-06-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_producto_foto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
